language: python
sudo: false

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"

before_install:
  - pip install hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin

install:
  - luarocks make
  - luarocks install luacov-coveralls

script:
  - lua tests/tests.run --luacov

after_success:
  - mv tests/luacov.stats.out . && luacov-coveralls -c tests/.luacov
